Create slides and samples for synchronization (#85)
anz-bank/go-slides pull request #86
Opened 2019-05-19 02:12 UTC by linuxmonk

Addresses issue #83

2019-05-21 03:01 UTC, anzboi requested changes
I would like to clean up the slide.
The examples are good. Normally I would advise against code that doesn't run, but in this case I think it is fine.

2019-05-21 03:01 UTC, anzboi commented on content/gocourse-2019-05-melbourne.slide
> +- High level Synchronization primitives `WaitGroup` and `Once`
Synchronization shouldn't be capitalized
Also feel like there should be a `:` between 'primitives' and 'WaitGroup'

2019-05-21 03:01 UTC, anzboi commented on content/gocourse-2019-05-melbourne.slide
> +- Intended for low level programming `Mutex`, `RWMutex`, `Cond`
This reads a little strange as it is
suggestion: Low level synchronization primitives: ...

2019-05-21 03:01 UTC, anzboi commented on content/gocourse-2019-05-melbourne.slide
> +- [[https://play.golang.org/p/OUAncJlBbmS][Unmatched `waitgroup.Add()` and `waitgroup.Done()` calls]]
The bold blocks look odd in this link.

2019-05-21 03:01 UTC, anzboi commented on content/gocourse-2019-05-melbourne.slide
> +- Synchronization primitives are used for orchestration, Channels are used for communication
I'm guessing this is meant to lead on into Channels. IMO leave channels information under channels slide.
I also feel like this line would better go as the first line on this slide.

2019-05-21 06:18 UTC, juliaogris commented on samples/goroutines5.go
> +
unnecessary blank lines.

2019-05-22 14:33 UTC, linuxmonk commented
I am planning to close this PR as we've decided to cover channels.

2019-05-26 23:17 UTC, camh-anz commented
@linuxmonk If this is meant to be closed, could you close it please? It would be nice to get the number of open pull requests down to zero before the course starts today. Thanks.

2019-05-26 23:20 UTC, linuxmonk commented
Closing as per earlier discussions

2019-05-26 23:20 UTC, closed without merging