Add slide with links for further reading
anz-bank/go-slides pull request #96
Opened 2019-05-26 07:25 UTC by anzboi

This PR adds a slide with topics of interest that are not covered in the course. Purpose is to give the audience an idea of what else is out there for go developers.

2019-05-26 07:34 UTC, camh-anz commented on content/gocourse-2019-05-melbourne.slide
> +- [[https://golang.org/pkg/runtime/pprof/][CPU/Mem Profiling][]]
There seems to be an extra `[]` after the link text.

2019-05-26 07:34 UTC, camh-anz commented on content/gocourse-2019-05-melbourne.slide
> +- [[https://appliedgo.net/plugins/][Plugins]]
"Plugins" is a bit too generic. How about "Writing plugins in Go"?

2019-05-26 07:34 UTC, camh-anz commented on content/gocourse-2019-05-melbourne.slide
> +- [[https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go][Benchmarks]]
"Benchmarks" is too generic (is it Go compiler benchmarks, standard benchmarks written in Go, or something else).

How about "Benchmarking your code"?

2019-05-26 07:34 UTC, camh-anz commented on content/gocourse-2019-05-melbourne.slide
> +- [[https://golang.org/pkg/runtime/pprof/][CPU/Mem Profiling][]]
s/Mem/Memory/

2019-05-26 08:07 UTC, camh-anz commented
Hmmm, you've added the `labs.md` generation comment to the wrong commit.

2019-05-26 08:39 UTC, anzboi commented
Yeah I've screwed up my commits

2019-05-26 10:25 UTC, juliaogris requested changes
For some reason the PR is still labelled with `Review required`, here we go then:
once all of @camh-anz 	concerns & the git commit message update are address, good to go :)

2019-05-26 10:51 UTC, camh-anz commented
Yeah, it's still review required because I don't like the behaviour of "request changes". But I guess now that the status is reflected on the PR list page, I should get over myself and use it.

2019-05-27 00:37 UTC, anzboi commented
Deployment added:
https://pr96-dot-gotraining-testing.appspot.com/gocourse-2019-05-melbourne.slide#92

2019-05-27 00:51 UTC, camh-anz commented
@anzboi your initial commit still has the erroneous message about `labs.md`

2019-05-31 05:08 UTC, juliaogris approved these changes
LGTM

2019-06-04 23:33 UTC, merged